### PR TITLE
[PR] Bug: timer delay when app is in background

### LINKED ISSUE #8: Timer slows down when Electron app window not focused
## Steps to reproduce
1. Start a timer in the app, at the same time start a timer on your phone or wherever you want outside of the app. 
2. Navigate to a different application on your laptop so that the timetrk window is no longer the focused app on the desktop. 
3. After some seconds, refocus on the timetrk app and compare the time shown there with the control timer you started alongside this one in the beginning. 

## What the expected result is and what actually happens
*Expected*: Both timers have elapsed equally far. 
*Actual*: External control timer has elapsed further than the timetrk timer. The longer you leave timetrk out of focus, the larger the difference between time elapsed of the two timers is.

## Version
1.0 Initial Release

### PR DESCRIPTION
**Pull request by anjakDev**
The timer delay that was caused by the inaccuracy of setInterval due to JavaScript's single-threadedness should be fixed now. 
I followed the advice by https://medium.com/@abhi9bakshi/why-javascript-timer-is-unreliable-and-how-can-you-fix-it-9ff5e6d34ee0 and https://www.sitepoint.com/build-javascript-countdown-timer-no-dependencies/ to use Date objects to count down with. 

Closes #8

### CODE REVIEW

File: src/utils/PomodoroTimer.js [hunk 1]
```diff
@@ -5,20 +5,32 @@ export const PomodoroTimer = {
     seconds = seconds || 0;
     seconds = seconds + minutes * 60;
 
+    const immutableseconds = seconds
+
+    let end = new Date()
+    end.setSeconds(end.getSeconds() + immutableseconds)
```
Comment (phipsp) [inline src/utils/PomodoroTimer.js:11]: I don't know if we need `immutableseconds`. Perhaps this is sufficient:

```suggestion
    end.setSeconds(end.getSeconds() + seconds)
```

**Review by phipsp — CHANGES_REQUESTED** [review]
Good stuff 💯

File: src/utils/PomodoroTimer.js (hunk 1 above)
Comment (anjakDev) [reply src/utils/PomodoroTimer.js]: done

**Review by phipsp — APPROVED** [review]
🚀
